### PR TITLE
add "publish on twitter" support.

### PR DESCRIPTION
**Pull request by tedder**
other changes:
- rename http to twhttp. Conflicts with 'import http.server' deep inside oauth2.
- add config example and docu to README

### CODE REVIEW

**Comment by timofurrer** [comment]
Why don't we allow to have multiple post tweet hooks and outsource the twitter publishing in a hook?
There are other platforms like twitter - if we, one day, want to support them too - we'll end up in a mess of service specific code inside twtxt.

**Comment by tedder** [comment]
Totally understand that idea. I thought about making the hooks a list. It certainly works well with the indieweb POSE model. On the other hand, dealing more natively with Twitter made sense too. Do you have ideas of how the extension concept could be implemented?

**Comment by timofurrer** [comment]
If we would implement extensions you'd have the advantages of both. I'd have some ideas. There are many examples around on how to implement extensions/plugins in python..
Do you think there'd be more twitter integration then just republishing?

**Comment by tedder** [comment]
I don't see there being much more depth to the twitter integration, but others may disagree (perhaps by combining it into the twtxt timeline?).

Want to put out a basic pull request with an initial extension framework? I can then rebuild this on top of it.

**Comment by timofurrer** [comment]
Let's wait what others thoughts are about this before starting anything *stupid* :beers:

**Comment by kitchen** [comment]
+1 on framework idea. I'm also bullish on integrating early, factoring out common things into extractable plugins later. Often you don't know the API you want to expose until you've written a few consumers of it.

I wonder if there are some app.net or identi.ca users who might want to help flesh out the idea some more?

**Comment by buckket** [comment]
I really don’t like the idea to include Twitter (or any other service) support in twtxt. Keeping the main application clean and simple while solving only one problem is my main focus here.

But I can understand why people might want to use this, so in the long run implementing a plugin interface/system, which allows to add hooks seems the best solution.

**Comment by tedder** [comment]
@buckket are you thinking about extensions being in their own python module (pip install twtxt-twitter) or as part of this one (import twtxt.extensions.twitter)?

**Comment by buckket** [comment]
@tedder I’d prefer them being separate modules.

**Comment by buckket** [comment]
Closing this for now until we have a plugin system set up.

**Pull request closed without merging**
