### PR TITLE
Add config CLI command to edit twtxt config file

### PR DESCRIPTION
**Pull request by timofurrer**
This command behaves similar to other `config` CLI commands
for example the one from git:

``` bash
$ twtxt config twtxt.nick tuxtimo  # set nick
$ twtxt config twtxt.nick  # get nick
tuxtimo
$ twtxt config --remove twtxt.nick  # remove nick
$ twtxt config --edit  # edit config file with editor
```

### CODE REVIEW

**Comment by DracoBlue** [comment]
Nice! Can you modify README/docs, too?

**Comment by timofurrer** [comment]
Sure, I will asap.

**Comment by buckket** [comment]
For editing you could use: http://click.pocoo.org/5/utils/#launching-editors
Instead of catching all exceptions silently you should at least log them via logger.debug().

**Comment by timofurrer** [comment]
I'll use the `click` method - I'll update the PR as soon as I'm at home.

**Comment by timofurrer** [comment]
Update PR accordingly!

**Pull request merged**
