### PR TITLE
Store tweet hashes and check them before tweeting to prevent duplicates.

### PR DESCRIPTION
**Pull request by Samathy**
Maybe tweet hashes could be implemented in the meta-data of a tweet in the future. But for now, store it in another file.

### CODE REVIEW

**Comment by jomo** [comment]
I was thinking about hashing the complete line (i.e. including the time stamp) as an identifier for tweets, which then could be used to reply to a specific tweet.

**Comment by Samathy** [comment]
Storing the timestamp makes sense, yeah. Will implement that in another branch.

**Comment by timofurrer** [comment]
Why is it a problem to tweet something multiple times? 
This implementation could lead into performance issues when you have a lot of tweets.

**Comment by buckket** [comment]
I agree with @timofurrer. Don’t see why this is problem that needs special attention right now.

**Comment by Samathy** [comment]
It doesnt need special attention, I guess I'm just trying to contribute some stuff!  I appreciate your standing.

**Comment by buckket** [comment]
Your contribution is much appreciated, but right now I want to get the other things (mentions, more tests) done first, while increasing the complexity of the code base as little as possible. I’m closing this for now, and may come back to it later. Hope that’s fine with you. (ﾉﾟ-ﾟ)ﾉ

**Pull request closed without merging**
