### PR TITLE
Add `twtwt` client

### PR DESCRIPTION
**Pull request by win0err**
I've added a link to [twtwt](https://github.com/win0err/twtwt) client (an implementation written in C).
It supports Linux/BSD/macOS.

### CODE REVIEW

**Comment by prologic** [comment]
Maybe you'd like to add it here too: https://git.mills.io/mckinley/groovy-twtxt ?

**Comment by win0err** [comment]
> Maybe you'd like to add it here too: https://git.mills.io/mckinley/groovy-twtxt ?

Yes, I'd like to add, but I'm too lazy to register on mills.io :-)

**Comment by prologic** [comment]
I'll add an account that matches your GitHub account and you can use GitHub to auth👌

**Comment by prologic** [comment]
I do need an email from you though. Can you please drop me a quick email? 🙏

**Comment by prologic** [comment]
Nevermind, found it on your website 👌

**Comment by buckket** [comment]
Thanks, great work!

**Pull request merged**
