### PR TITLE
Implement view command to view feed of specific source

### PR DESCRIPTION
**Pull request by timofurrer**
Implements feature requested in Issue #9

### CODE REVIEW

**Comment by buckket** [comment]
This adds too much redundancy in my opinion.

Thought about adding an option to the timeline command like so:
`twtxt timeline --source=buckket`

We could than create an alias which calls the above command:
`twtxt view buckket` results in calling `twtxt timeline --source=buckket` internally

**Comment by timofurrer** [comment]
I'll update the PR

**Comment by timofurrer** [comment]
@buckket It's now implemented as you requested :beers:

**Comment by buckket** [comment]
Merged and updated. Should do the trick for now.

But maybe there is a better way to handle this, having to write all the decorators and the default config options twice bothers me. Maybe I’ll ask someone over at the click project later.

**Pull request closed without merging**
