### PR TITLE
Updated Docstrings

### PR DESCRIPTION
**Pull request by Altoyyr**
Hello buckket,

I updated the docstrings of the twtxt/config.py because all the :param where missing.
Also added a docstring for models.Source and added a newline to the end of __main__.py to follow PEP8.

I look forward to contribute more in the future.
Altoyyr

### CODE REVIEW

**Comment by timofurrer** [comment]
Could you add the types to the param documentation? and you might want to squash your commits.

**Comment by Altoyr** [comment]
Sure I will add the types.
I prefer to keep my commits as small as possible to simplify the reviewing-process, but I think in that case I could squash the ones adding the docstrings to config.*

I will fix this when I get home after work.

**Comment by timofurrer** [comment]
Thanks.

For the param types you should do something like this:

```
:param str url: the feed URL to fetch
```

**Comment by Altoyyr** [comment]
Hey,
I fixed the types - hopefully - to your liking.

They are now recognized by pycharm.

**Comment by buckket** [comment]
Instead of writing `attributes:` it’s better to stick to the `:param foo: bar` notation when documenting the `__init__` parameters of a class. ([example](https://github.com/mitsuhiko/click/blob/master/click/types.py#L342)) Apart from that it looks fine! Thanks for contributing. :+1:

**Comment by Altoyyr** [comment]
Ok, got it.
I fixed that too.


Offtopic, is there some kind of mailing lists where you could discuss questions or should one open a ticket?

**Comment by Altoyyr** [comment]
Sorry for making this pull-request so messy, but i rebased on the master to increase graph-readability

**Comment by timofurrer** [comment]
there is an IRC channel #twtxt on FreeNode or you could use gitter - There is a badge in the README with a link to the gitter chat - it's pretty convenient.

**Pull request merged**
