### PR TITLE
Use relative imports instead of absolute

### PR DESCRIPTION
**Pull request by timofurrer**

### CODE REVIEW

**Comment by tedder** [comment]
is this common practice?

**Comment by timofurrer** [comment]
Yes, it is. Check out requests, flask or other well coded python packages ;)

**Comment by buckket** [comment]
I don’t like (explicit) relative imports, and I don’t see any obvious benefits when using them.

**Comment by timofurrer** [comment]
There is the benefit that you have to type less ... Is there a benefit to use absolute imports for modules in your own package?

**Pull request closed without merging**
